---
  - name: Generate RSA key
    command: openssl genrsa -out {{ssl_certs_path}}/{{item}}.key {{ssl_certs_key_size}} creates={{ssl_certs_path}}/{{item}}.key
    with_items: "{{ domains }}"

  - name: Generate CSR
    command: openssl req -new -subj '{{ssl_certs_fields}}' -key {{ssl_certs_path}}/{{item}}.key -out {{ssl_certs_path}}/{{item}}.csr creates={{ssl_certs_path}}/{{item}}.csr
    with_items: "{{ domains }}"

  - name: Generate self-signed SSL certificate
    command: openssl req -nodes -x509 -days {{ssl_certs_days}} -in {{ssl_certs_path}}/{{item}}.csr -key {{ssl_certs_path}}/{{item}}.key -out {{ssl_certs_path}}/{{item}}.crt -extensions v3_ca creates={{ssl_certs_path}}/{{item}}.crt
    when: ssl_certs_generate_self_signed
    with_items: "{{ domains }}"
