---
nginx_user: "vagrant"
nginx_use: "epoll"

nginx_worker_processes: "2"
nginx_worker_connections: "1024"
nginx_worker_rlimit_nofile: "1024"
nginx_multi_accept: "on"

nginx_log_format_name: "main"
nginx_error_log_level: "warn"

nginx_dir_main: "/etc/nginx"
nginx_dir_log: "/var/log/nginx"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k"

nginx_sendfile: "on"
nginx_tcp_nopush: "off"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_client_max_body_size: "500M"

nginx_proxy_cache_path: ""

nginx_gzip: "on"
nginx_gzip_disable: "MSIE[1-6]\\.(?!.*SV1)"
nginx_gzip_types: "text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/rss+xml application/atom+xml application/rdf+xml"

nginx_remove_default_vhost: true

server_blocks: "{{ server_blocks }}"

nginx_upstreams: []
