---
- name: Update System packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Copy the system clock file
  template:
    src: clock.j2
    dest: "{{ clock_path }}"
    backup: yes
    group: root
    owner: root

- name: Create localtime Symbolic Link
  file:
    src: "{{ zone_info_path }}/{{ system_timezone }}"
    dest: "{{ localtime_path }}"
    owner: root
    group: root
    state: link
    force: yes